---
title: "4_ts_figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(tidyverse)
library(gbm)
library(dismo)
library(ggpubr)

panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y, use = "complete.obs"))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor * r)
}

panel.hist <- function(x, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}

```

# AFS presenatation

Figure of high versus low thermal sensitivity.

```{r}
dat <- readRDS("data_preparation/final_data/summer_data_wair2021-11-23.rds")

dat <- dat %>% 
  mutate(year = year(sampleDate))

```


```{r}
dat %>% 
  filter(SiteID %in% c("CIK_14", "CIK_3"), year %in% c(2013, 2015, 2019)) %>%
  mutate(site = case_when(SiteID == "CIK_14" ~ "Anchor River",
                          TRUE ~ "Chester Creek")) %>% 
  ggplot() +
  geom_line(aes(x = sampleDate, y = airDT)) +
  geom_line(aes(x = sampleDate, y = meanDT), color = "blue") +
  facet_grid(vars(site), vars(year), scales = "free_x") +
  theme_bw() +
  labs(x = "Date", y = "Temperature")

```

# TS figures

Read in metrics data frame.

```{r}
mets <- readRDS("output/metrics_2022-02-17.rds")

mets %>% 
  count(subset1)
mets %>% 
  filter(subset1 == 0) %>% 
  distinct(Site, Year)

mets %>% 
  filter(subset1==1 & deshka ==1) %>% 
  distinct(Site, Year) %>% 
  count(Site)
```

Plot of stream TS by region. Remove extra deshka sites.

```{r}
mets %>%
  filter(subset1 == 1, Year %in% 2011:2019, !is.na(TempSens)) %>% 
  count(Region, Year) %>% 
  pivot_wider(names_from = Year, values_from = n, names_sort = TRUE)


mets %>%
  filter(subset1 == 1, Year %in% 2011:2019, !is.na(TempSens)) %>% 
  group_by(Region, Year) %>% 
  mutate(count = n(), 
         Region = gsub("_", " ", Region)) %>% 
  filter(count > 7) %>% 
  ggplot() +
  geom_boxplot(aes(y = TempSens, x = as.factor(Year), fill = Region)) +
  theme_bw() +
  theme(text = element_text(size = 18)) +
  labs(x = "Year", y = "Thermal Sensitivity")

ggsave("output/presentation_figs/ts by region and year.jpeg", width = 12, height = 8)

```


## pca

Build-up of PCA

```{r}
mets_12 <- c("MA7d_DMT", "RANGE_MAX", "SIGMA_DMT", "SUM_13_DMT", "SUM_18_DMT", "dur13mx", "dur18mx",
             "MxDMT_jd", "MA7d_DMT_jd", "NDNT", "TempSens", "MnDAT", "RANGE_MN", "MxDMT")

mets %>% dplyr::select(one_of(mets_12)) %>% summary()

pca_in <- mets %>% dplyr::select(one_of(mets_12), Region) %>% filter(!is.na(TempSens)) %>% mutate(Region = gsub("_", " ", Region))

pca1 <- princomp(x = pca_in %>% dplyr::select(-Region), cor = TRUE)

biplot(pca1)

#basic pca 
autoplot(pca1, data = pca_in, colour = 'Region', loadings.label = FALSE, loadings.label.repel = TRUE,
         frame = FALSE, frame.type = "t", frame.colour = 'Region', loadings.label.col = "black") +
  theme_bw() +
  theme(text = element_text(size = 18)) 
  
ggsave("output/presentation_figs/pca1_basic.jpeg", width = 12, height = 8)

autoplot(pca1, data = pca_in, loadings.label = TRUE, loadings.label.repel = TRUE,
         loadings.label.size = 5, colour = 'Region', loadings.label.col = "black",
         loadings.col = "black") +
  # scale_color_manual(values = rep("gray", 5)) +
  theme_bw() +
  theme(text = element_text(size = 18)) 
  
ggsave("output/presentation_figs/pca1_biplot.jpeg", width = 12, height = 8)

autoplot(pca1, data = pca_in, colour = 'Region', loadings.label = FALSE, loadings.label.repel = TRUE,
         frame = TRUE, frame.type = "norm", frame.colour = 'Region', loadings.label.col = "black",
         loadings.col = "black", loadings.label.size = 5) +
  theme_bw() +
  theme(text = element_text(size = 18)) 
  
ggsave("output/presentation_figs/pca1_regions.jpeg", width = 12, height = 8)

```


# metrics pairplot

```{r}

jpeg(filename = "output/presentation_figs/metrics_pairplot.jpeg", width = 12, height = 8, units = "in", res = 100)
mets %>% 
  dplyr::select(TempSens, RANGE_MAX, MA7d_DMT, MA7d_DMT_jd) %>% 
  filter(!is.na(TempSens)) %>% 
  pairs(., diag.panel = panel.hist, upper.panel = panel.cor, lower.panel = panel.smooth)
dev.off()

```

# brt figures

Bring in saved brts.

```{r}
brt_step <- read_rds("output/brt_tc5_lr005.rds")

cv.dev <- brt_step$cv.statistics$deviance.mean
null.dev <- brt_step$self.statistics$mean.null
train.dev <- brt_step$self.statistics$mean.resid

dev.exp <- (null.dev - cv.dev)/null.dev #cross validated deviance explained
dev.exp.train <- (null.dev - train.dev)/null.dev #training deviance explained

brt_step$contributions %>% 
  mutate(var_names = case_when(var == "wtd_slope_MEAN" ~ "Watershed slope",
                               var == "log_cat_elev" ~ "Catchment elevation",
                               var == "asrt_lake" ~ "Lake cover",
                               var == "log_area" ~ "Watershed size",
                               var == "summer_precip" ~ "Summer precipitation",
                               var == "dist_coast_km" ~ "Distance to coast",
                               var == "snow_ind" ~ "Snow index",
                               var == "asrt_wet" ~ "Wetland cover",
                               var == "log_cat_slope" ~ "Catchment slope",
                               var == "log_slope" ~ "Stream gradient",
                               var == "wtd_north_per" ~ "North aspect",
                               var == "asrt_glac" ~ "Glacier cover",
                               TRUE ~ var)) %>% 
  ggplot(aes(x = rel.inf, y = fct_reorder(var_names, rel.inf))) +
  geom_col() +
  theme_bw() +
  theme(text = element_text(size = 18), axis.title.y = element_blank()) +
  labs(x = "Relative Variable Importance")

ggsave("output/presentation_figs/brt_varimp.jpeg", width = 10, height = 8)


```


```{r}
brt_gbm <- readRDS("output/brt-gbm_tc5_lr005.rds")

gbm.plot(brt_step, smooth = TRUE, n.plots = 10, rug = TRUE,
         plot.layout = c(2,2)) #plots of first order relationships

gbm.plot(brt_step, smooth = TRUE, variable.no = 13, rug = TRUE,
         plot.layout = c(2,2)) #plots of first order relationships

pdp::partial(brt_step, pred.var = c("snow_ind", "log_area"),chull = TRUE, plot = TRUE, n.trees = 8300, rug = TRUE,
             train = brt_in)
pdp::partial(brt_step, pred.var = c("snow_ind", "wtd_slope_MEAN"),chull = TRUE, plot = TRUE, n.trees = 8300, rug = TRUE, train = brt_in)
pdp::partial(brt_step, pred.var = c("Region"),chull = TRUE, plot = TRUE, n.trees = 8300, rug = TRUE, train = brt_in)

brt_int <- gbm.interactions(brt_step)
brt_int$rank.list

interact.gbm(brt_gbm, data = brt_in, i.var = c("snow_ind", "log_area"))
interact.gbm(brt_gbm, data = brt_in, i.var = c("Region", "wtd_slope_MEAN"))

pdf("pdp plots for brt.pdf")
for(i in 1:nrow(brt_int$rank.list)) {
  x1 <- brt_int$rank.list %>% slice(i) %>% pull(var1.names)
  x2 <- brt_int$rank.list %>% slice(i) %>% pull(var2.names)
  int_H <- interact.gbm(brt_gbm, data = brt_in, i.var = c(x1, x2))
  plot_title <- paste("H-statistic: ", round(int_H, 2))
  pd <- pdp::partial(brt_step, pred.var = c(x1,x2), chull = TRUE, n.trees = 8300, rug = TRUE, 
                     train = brt_in)
  if(x1 == "Region"|x2 == "Region") {
    p1 <- ggplot(data = pd) +
      geom_point(aes(x = wtd_slope_MEAN, y = yhat, color = Region)) 
    print(p1)
  } else {
    p1 <- plotPartial(pd, main = plot_title, type = "regression")
    print(p1)
  }
}
dev.off()
```


```{r internal cv predictions}
brt_out <- brt_in %>% 
  mutate(preds = predict(brt_step),
         cv.preds = brt_step$fold.fit)

brt_out %>% 
  mutate(Region = gsub("_", " ", Region)) %>% 
  ggplot(aes(x = cv.preds, y = TempSens)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline(aes(slope = 1, intercept = 0)) +
  facet_wrap(~Region) +
  coord_cartesian(xlim = c(-0.2, 0.8), ylim = c(-0.2, 0.8)) +
  stat_regline_equation(label.x = -0.2, label.y = c(seq(0.75, 1, 0.1)),
                        aes(label = ..eq.label..)) +
  stat_regline_equation(label.x = -0.2, label.y = c(seq(0.6, 1, 0.1)),
                        aes(label = ..adj.rr.label..)) +
  theme_bw() +
  labs(y = "Observed Thermal Sensitivity",x = "Predicted Thermal Sensitivity") +
  theme(text = element_text(size = 18))

ggsave("output/presentation_figs/brt OP plot.jpeg", width = 10, height = 8) 
```


```{r internal cv predictions}

brt_out %>% 
  ggplot(aes(x = cv.preds, y = TempSens)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline(aes(slope = 1, intercept = 0)) +
  coord_cartesian(xlim = c(-0.2, 0.8), ylim = c(-0.2, 0.8)) +
  stat_regline_equation(label.x = -0.2, label.y = c(seq(0.75, 1, 0.1)),
                        aes(label = ..eq.label..)) +
  stat_regline_equation(label.x = -0.2, label.y = c(seq(0.6, 1, 0.1)),
                        aes(label = ..adj.rr.label..)) +
  theme_bw() +
  labs(y = "Observed Thermal Sensitivity",x = "Predicted Thermal Sensitivity") +
  theme(text = element_text(size = 18))

# ggsave("output/presentation_figs/brt OP plot.jpeg", width = 10, height = 8) 
```


```{r rmse of internal cv predictions}
brt_out %>% 
  mutate(sqerror = (TempSens - cv.preds)^2) %>% 
  summarize(sqrt(sum(sqerror)/1666))
```


```{r plot of brt predictors}

gbm.plot(brt_step, smooth = TRUE, n.plots = 8) #plots of first order relationships


```


```{r brt interaction}

pd <- pdp::partial(brt_step, pred.var = c("snow_ind", "log_area"), 
              n.trees = 8650, train = brt_in, plot = TRUE, chull = TRUE)


plotPartial(pd, rug = TRUE, train = brt_in, chull = TRUE)


```
 
 