---
title: "datat_PWSSC"
author: "dwmerrigan"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, messages = FALSE)
knitr::opts_knit$set(root.dir = normalizePath("..")) #this sets the root.dir up one level back to the project so that paths are relative to the project directory.

library(readxl)
library(xlsx)
library(stringr)
library(lubridate)
library(googlesheets4)
library(rnoaa)
library(hms)
library(tidyverse)
library(googledrive) 

getwd()

```

```{r Functions}
getwd()
# Source functions in helper function script to ensure proper format of saved data
source("helper_functions.R")

acronym = "PWSCC_"

```


# Read in data and format

```{r Format temp data}
getwd()
# Folder containing source datasets
source_fol <- ".\\source\\15_PWSSC"

files <- list.files(source_fol, full.names = T, recursive = T, pattern = ".*.csv|.*.xlsx")
basename(files)

for (file in files){
  filename <- basename(file)
  sitename <- paste0(acronym,sub("_.*","", filename))
  print(sitename)
  
}
# Tibble to store temp data
pwssc_dat <- tibble()

for (i in files) {
  filename <- basename(i)
  print (filename)
  sitename <- paste0(acronym,sub("_.*","", filename))
  dat <-  read_csv(file = i, col_types = "ncn" )
  colnames(dat) <- c("id","datetime", "Temperature")
  dat <- dat %>% 
    mutate(SiteID = sitename,
           data_filename = filename,
           dt = as.POSIXct(datetime, format = "%m/%d/%y %H:%M", tz = "GMT"),
           sampleDate = as_date(dt),
           sampleTime = as_hms(dt),
           year = year(sampleDate),
           UseSite = 1,
           UseData = 1)
  pwssc_dat <- bind_rows(pwssc_dat, dat[!is.na(dat$Temperature),]) %>% 
   select(SiteID,
          dt,
          sampleDate,
          sampleTime,
          year,
          Temperature,
          UseSite,
          UseData)
}
summary(pwssc_dat)

```
# Create Metadata File
Metadata not in AKOATS 

```{r Create Metadata}
# Get Site IDs
dput(unique(pwssc_dat$SiteID))
# Build Metadata
pwssc_md <- tibble(SiteID = c("PWSCC_Erb", "PWSCC_Gilmour",
                               "PWSCC_Hogan", "PWSCC_Stockdale"),
                   Waterbody_name = c("Erb Creek" ,"Gilmour Creek",
                                      "Hogan Creek", "Stockdale Creek"),
                   Latitude = c("","","",""),
                   Longitude = c("","","","")) %>% 
  mutate( seq_id = NA,
          SourceName = "PWSSC",
          Agency_ID = SiteID,
          SourceName = "PWSCC",
          Contact_person = "Pete Rand",
          Contact_telephone = NA,
          Contact_email = "psrand@gmail.com",
          Sensor_Placement = NA,
          Waterbody_type = "S",
          Sensor_accuracy = NA,
          Sensor_QAQC = NA)

pwssc_md
```

# Save Data
Sites not in AKOATS so Metadata will be limited to what is available from provider

```{r Save Data}
# Save Metadata
akoats_fields <- c ("SiteID", "seq_id", "Agency_ID", "SourceName", "Contact_person", 
                     "Contact_email", "Contact_telephone", "Latitude", "Longitude", 
                     "Sensor_Placement", "Waterbody_name", "Waterbody_type", "Sensor_accuracy", 
                     "Sensor_QAQC")
pwssc_md <- pwssc_md %>% 
  select(all_of(akoats_fields))

save_metadata_files(pwssc_md, acronym)

# Save Temp data

pwssc.data <- pwssc_dat %>% 
  distinct()

pwssc.data.qc <- pwssc.data %>% 
  filter( month(sampleDate) %in% 6:9)

saveRDS(pwssc.data.qc, "formatted_data/pwssc.data.rds")

summary(pwssc.data)

```

# Create Pdf of Raw Temp by site/year 
Limit to period of interest June-September

```{r Rolling pdf of temp by site/year}
getwd()

pwssc_sites <- pwssc.data.qc %>% distinct(SiteID, year) %>% arrange(SiteID, year)

pdf("PWSSC Raw Data by Site and Year.pdf", width = 11, height = 8.5)
# Get limits of temp data 
for(i in 1:nrow(pwssc_sites)) {
  dat <- left_join(pwssc_sites %>% slice(i), pwssc.data.qc)
  subtitle <- dat %>% distinct(UseSite) %>% pull(UseSite)
  xmin <- as.POSIXct(min(dat$dt),format = "%Y-%m-%d %H:%M")
  xmax <- as.POSIXct(max(dat$dt),format = "%Y-%m-%d %H:%M")
  p1 <- dat %>% 
    ggplot(aes(x = dt, y = Temperature)) +
    geom_line() +
    scale_x_datetime(limits = c(xmin, xmax), labels = waiver()) +
    scale_y_continuous(limits = c(-5, 30), labels = waiver()) +
    labs(title = pwssc_sites %>% slice(i) %>% unite(site_year) %>%
           pull(site_year),
         subtitle = paste0("Use Site: ", subtitle)) +
    theme(legend.position = "bottom")
  print(p1)
}

dev.off()

```